apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fl-results
  namespace: nt114-fl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data
  namespace: nt114-fl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi