apiVersion: v1
kind: ConfigMap
metadata:
  name: fl-config
  namespace: nt114-fl
data:
  WEB3_PROVIDER_URI: http://ganache:7545
  IPFS_API_ADDR: /dns4/ipfs/tcp/5001/http
  CONTRACT_ARTIFACT: /app/build/contracts/Reputation.json
  CONTRACT_ADDRESS_FILE: /results/runtime/reputation-address.json
  SERVER_ADDRESS: fl-server:8080
  SPLIT_TYPE: non_iid