apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fl-results
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nt114-fl.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.resultsSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nt114-fl.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.ipfsSize }}